<?php
/**
 * @category	design
 * @package		Iparcel_Shipping
 * @author     Bobby Burden <bburden@i-parcel.com>
 * @class			Iparcel_Shipping_Block_Adminhtml_Sales_Order_Shipment_View_Tracking
 */
?>
<div class="field-row grid" id="shipment_tracking_info">
<table cellspacing="0" class="data">
    <col width="100" />
    <col />
    <col />
    <col width="80" />
    <thead>
        <tr class="headings">
            <th><?php echo Mage::helper('sales')->__('Carrier') ?></th>
            <th><?php echo Mage::helper('sales')->__('Title') ?></th>
            <th><?php echo Mage::helper('sales')->__('Number') ?></th>
        </tr>
    </thead>
<?php if($_tracks = $this->getShipment()->getAllTracks()): ?>
    <tbody>
    <?php $i=0;foreach ($_tracks as $_track):$i++ ?>
        <tr class="<?php echo ($i%2==0)?'even':'odd' ?>">
            <td><?php echo $this->escapeHtml($this->getCarrierTitle($_track->getCarrierCode())) ?></td>
            <td><?php echo $this->escapeHtml($_track->getTitle()) ?></td>
            <td>
                <?php if ($_track->isCustom()): ?>
                <?php echo $this->escapeHtml($_track->getNumber()) ?>
                <?php else: ?>
                <a href="#" onclick="popWin('<?php echo $this->helper('shipping')->getTrackingPopupUrlBySalesModel($_track) ?>','trackorder','width=800,height=600,resizable=yes,scrollbars=yes')"><?php echo $this->escapeHtml($_track->getNumber()) ?></a>
                <div id="shipment_tracking_info_response_<?php echo $_track->getId() ?>"></div>
                <?php endif; ?>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
<?php endif; ?>
</table>
</div>
