<?php
/**
 * @category	design
 * @package		Iparcel_Shipping
 * @author		Patryk Grudniewski <patryk.grudniewski@sabiosystem.com>
 * @class			Iparcel_Shipping_Block_Catalog_Product_List
 */
?>
<?php
$_productCollection = $this->getLoadedProductCollection();
?>
<script type="text/javascript">
	iparcelPost.sku_list({
		<?php foreach ($_productCollection as $_product): ?>
		"<?php echo $_product->getSku(); ?>": "<?php echo $_product->getName(); ?>",
		<?php endforeach; ?>
	});
	iparcelPost.stock_list({
		<?php foreach ($_productCollection as $_product): ?>
		"<?php echo $_product->getName(); ?>": "<?php echo $this->getStock($_product); ?>",
		<?php endforeach; ?>
	});
</script>
