<?php
/**
 * @category	design
 * @package		Iparcel_Shipping
 * @author		Patryk Grudniewski <patryk.grudniewski@sabiosystem.com>
 * @class			Iparcel_Shipping_Block_Html_Head_Jquery
 */
?>
<?php if($this->getFlag()): ?>
<script type="text/javascript" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS); ?>iparcel/jQuery.js"></script>
<script type="text/javascript">jQuery.noConflict();</script>
<?php endif; ?>
